### ISSUE TITLE
Verilator Error

### ISSUE THREAD

**Issue by kerimturak** [taneroksuz/mult-tree#2]
Verilator gives following error ,

`/usr/local/share/verilator/include/verilated_timing.h:51:11: fatal error: coroutine: No such file or directory
   51 | # include <coroutine>`

Is this related my WSL or do I need to use ubuntu instead of WSL.

My last question there are two output Z0 and Z1 in generated top module which one is the result?
I guest one of them low and one of them high part?

@taneroksuz

**Comment by taneroksuz** [comment]
Hi,

The problem with verilator is mentioned in https://github.com/verilator/verilator/issues/5262. It's already fixed in master branch. Unfortunately it's not included in stable branch yet. So you should adjust my installation script correctly to install verilator with master branch.

The wallace and dadda tree multiplier reduce the tree to two summand by end of the calculation. So they are not high or low part instead they are just addend which are added with proper addtion algorithm. The proper choice of summation algorithm is depend on the situtation. The addtion algorithms are slower than multiplier tree generator in general. Also when you include the tree multiplier in multiply accumulate unit, then you have tree summand instead of two. For specific purpose you should also implement an addition unit with proper algorithm to get result fast.

Best regards,
Taner Öksüz

**Comment by kerimturak** [comment]
Many thanks Taner,

I figure out now, I also got little slack at 50 MHz on basys3.
May fast summation algorithm fix it.
About verilator it does not work when you update gcc.
I guess it must be updated supported version before install verilator.
I fix it using another computer.

Kerim Turak,
